### ISSUE TITLE
message argument gets lost in Ember.Logger.error

### ISSUE THREAD

**Issue by danwenzel** [sir-dunxalot/ember-new-relic#11]
in `/instance-initializers/new-relic.js`, `Ember.Logger.error` gets reassigned to a new function.  `message, cause, stack` are passed in, but only `cause` and `stack` are used.  Unless I'm missing something, `message` would never get used.

According to the [Ember docs](http://www.emberjs.com.cn/api/classes/Ember.Logger.html#method_error), `Ember.Logger.error` is supposed to be called with just one argument, for the message.

**Comment by danwenzel** [comment]
Trying again... Anyone able to look at this?

**Comment by sir-dunxalot** [comment]
#13 Updates the calls to `Ember.Logger`. It doesn't appear to fix this issue exactly so I suggest seeing if @akatov uncovered any learnings about the params that should be passed to `Ember.Logger.error()` when making the PR.

If not, it's something I can look into in the future.

**Comment by sir-dunxalot** [comment]
One this to note is that the `Ember.Logger.error` documentation states "You can pass as many arguments as you want and they will be joined together with a space."

**Comment by danwenzel** [comment]
Just opened a PR that should fix this ⬆️

**Comment by sir-dunxalot** [comment]
Thanks @danwenzel!
