### ISSUE TITLE
Add ability to disable NewRelic in a specific environment to remove the warning during a build

### ISSUE THREAD

**Issue by denzo** [sir-dunxalot/ember-new-relic#16]
We would like to enable NewRelic only in a specific environment. Currently during the `development` build we get a warning like so:

![screen shot 2017-04-07 at 9 33 33 am](https://cloud.githubusercontent.com/assets/1874772/24779706/5852a446-1b75-11e7-9030-09016e478b0e.png)

Maybe a simple `enabled` flag?

**Comment by danwenzel** [comment]
👍  to this.  The documentation states:

> To enable New Relic Browser in certain environments, just include applicationId for those environments only

So if we do this, we should not be seeing the above warning.

**Comment by denzo** [comment]
@danwenzel you're right, the documentation does state that. However, this line suggests that both, `applicationId` and `licenseKey` are required to avoid the warning message.

https://github.com/sir-dunxalot/ember-new-relic/blob/master/index.js#L34

**Comment by danwenzel** [comment]
@denzo - Sorry, I wasn't clear.  I was saying that we _should_ not be seeing the above warning based on what the documentation says.  But as you point out, the code doesn't match the documentation.  So we're on the same page here 😄

**Comment by danwenzel** [comment]
@denzo @sir-dunxalot  - Just opened a PR that should fix this: https://github.com/sir-dunxalot/ember-new-relic/pull/17

**Comment by denzo** [comment]
@sir-dunxalot any update on this?

**Comment by GCheung55** [comment]
@denzo A fix was merged, is this still an issue?

**Comment by denzo** [comment]
Thanks so much everyone 🎉 🎉 🎉
