### ISSUE TITLE
EMBER_CLI_FASTBOOT no longer provided

### ISSUE THREAD

**Issue by mival** [sir-dunxalot/ember-new-relic#19]
while starting app using fastboot 1.0+ environment variable EMBER_CLI_FASTBOOT isn't set and so plugin inject NR javascript which crash

**Comment by jakeleboeuf** [comment]
+1 Needs the correct fastboot guard.

**Comment by williamweckl** [comment]
+1

**Comment by sir-dunxalot** [comment]
Fixed by #30.
