### ISSUE TITLE
loader.now is not a function

### ISSUE THREAD

**Issue by iamdtang** [sir-dunxalot/ember-new-relic#21]
I created a brand new 2.16 Ember app, installed the addon, and I get the following error:

![screenshot 2017-11-07 10 44 07](https://user-images.githubusercontent.com/687449/32511481-b8fa3094-c3a8-11e7-899d-2e4d4ae81f03.png)

Here is the relevant section in my `environment.js` file:

```js
  let ENV = {
    newRelic: {
      agent: 'js-agent.newrelic.com/nr-1044.js',
      licenseKey: 'my-key-here',
      applicationId: 'my-app-id-here',
      spaMonitoring: true
    }
  // ...
};
```

I did change the agent so that it is not the minified version so that I could see a better error message. I tried the minified version too and it produced the same error, but more cryptic.

**Comment by ewwilson** [comment]
I'm also getting the same error with the agent "js-agent.newrelic.com/nr-spa-1070.min.js"

**Comment by baileymiller182** [comment]
Getting the same error using the latest nr-spa-1071 (https://js-agent.newrelic.com/nr-spa-current.min.js)

**Comment by miguelcobain** [comment]
This doesn't seem to be happening with the latest new relic agent. This can probably be closed?

**Comment by sir-dunxalot** [comment]
This should be fixed by more recent New Relic agents. If you continue to see this issue we can reopen.
