### ISSUE TITLE
Update to use module imports

### ISSUE THREAD

**Issue by GCheung55** [sir-dunxalot/ember-new-relic#22]
https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md was merged and majority of modules have been made available on the `@ember` namespace.

`ember-new-relic` can use an update.

There are two problems that haven't been addressed, which is [how to treat `Ember.Logger`](https://github.com/emberjs/rfcs/pull/297) and [`Ember.onerror`](https://discuss.emberjs.com/t/ember-2-16-modules-api-how-to-import-ember-onerror/13717/4). But these two problems shouldn't be a blocker to begin updating. :)

**Comment by sir-dunxalot** [comment]
Fixed by #28.
