### ISSUE TITLE
How will addon be affected by new New Relic SPA update

### ISSUE THREAD

**Issue by djsegal** [sir-dunxalot/ember-new-relic#4]
article here: http://www.cio.com/article/3092978/application-development/new-relic-adds-support-for-golang-spa-monitoring.html

what effects will this have on this addon?

---

**edit:** better article here: https://blog.newrelic.com/2016/07/12/spa-public-beta/

**Comment by sir-dunxalot** [comment]
Thank you for sharing! I will need to look into this more but the article seems to suggest that not much will need to change and analytics tracking will just become more accurate.

The [docs](https://docs.newrelic.com/docs/browser/single-page-app-monitoring/get-started/add-apps-single-page-app-monitoring) also suggest the installation method is the same and that the user simply needs to turn on SPA monitoring in the New Relic app.

**Comment by jeremy-w** [comment]
The main change for this add-on is that the tracking script changes when you flip on SPA Monitoring:

> Customers who instrument RUM via their language agent will be upgraded automatically, while _copy/paste customers will be presented with a new JavaScript snippet for inclusion in the application._ (["Single-Page Application (SPA) Monitoring: Welcome to the Public Beta"](https://blog.newrelic.com/2016/07/12/spa-public-beta/), emphasis added)

This currently requires forking the add-on and hacking the tracking code bit. The simplest upgrade path might be to add a new config bit so `spaMonitoring: true` chooses the new, beta script, while `false` (the default) chooses the old, unless it's possible to use the new script with accounts not opted into the SPA Beta without error.

**Comment by jeremy-w** [comment]
I'm working on making the changes to support SPA today. Should have a PR later today.
