### ISSUE TITLE
Load New Relic script from external file

### ISSUE THREAD

**Issue by GCheung55** [sir-dunxalot/ember-new-relic#6]
In the context of CSP, `inline-unsafe` is... unsafe. To make an app safer, a sha hash generated from the script can be placed into CSP, or the script can be loaded from an external JS file.

**Comment by GCheung55** [comment]
Another alternative is to include the script as part of vendor.js.

**Comment by sir-dunxalot** [comment]
Thanks for the issue, Garrick. Any idea what the easiest way to implement one of your solutions in Ember CLI is?

**Comment by GCheung55** [comment]
@sir-dunxalot `broccoli-file-creator` could be leveraged to create/write a file with the contents that goes into the script tag. The file would then be optionally 1) imported into vendor.js file or 2) merge the file into the public tree and output a script tag to load the file in `contentFor`.

I'm not too familiar with the addon hooks so I'm currently determining where to do what and when.

**Comment by GCheung55** [comment]
@sir-dunxalot I've got something working but need some guidance. 

My approach is to maintain existing functionality and optionally write and load an external file with options provided in `ember-cli-build.js`. So it's basically inline the JS or write and load via external file, not both. 

Would that be acceptable or do younhave a different approach in mind?
